# Generated by Django 3.2.20 on 2023-08-27 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edx_careerpaths', '0004_rename_pathcourses_pathcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='pathcourse',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='edx_careerpaths.course'),
        ),
        migrations.AlterUniqueTogether(
            name='pathcourse',
            unique_together={('careerpath', 'course_id')},
        ),
        migrations.RemoveField(
            model_name='pathcourse',
            name='course_id',
        ),
    ]
