# Generated by Django 3.2.20 on 2023-08-27 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edx_careerpaths', '0005_auto_20230827_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathcourse',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edx_careerpaths.course'),
        ),
    ]
